# Generated by Django 4.0 on 2021-12-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(blank=True, max_length=40, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'phone_number',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sms_sender', to='messageapi.account')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sms_receiver', to='messageapi.account')),
            ],
            options={
                'db_table': 'sms',
            },
        ),
    ]
