# Generated by Django 4.0 on 2021-12-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messageapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sms_sender', to='messageapi.phonenumber'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sms_receiver', to='messageapi.phonenumber'),
        ),
    ]
